<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { appApi, getSession } from './api'

interface OnboardingState { step:number; use_case?:string; checklist:Record<string,boolean>; completed:boolean }
const state=ref<OnboardingState>({step:1,checklist:{},completed:false}), loading=ref(true), error=ref(''), saving=ref(false)
const useCase=ref('transactional'), company=ref(''), teamSize=ref('1-5')
const steps=[['profile','Tell us about your team'],['domain','Add a sending domain'],['sender','Verify a sender'],['api','Create an API credential'],['test','Send a test message']]
async function load(){try{const session=await getSession();if(!session.authenticated){location.assign('/login?return_to=/onboarding');return}state.value=await appApi<OnboardingState>('/app/api/onboarding');useCase.value=state.value.use_case||'transactional'}catch(err){error.value=err instanceof Error?err.message:'setup_unavailable'}finally{loading.value=false}}
async function saveStep(key:string,index:number){saving.value=true;error.value='';try{state.value=await appApi<OnboardingState>('/app/api/onboarding',{method:'PATCH',body:JSON.stringify({step:index+2,use_case:useCase.value,checklist:{[key]:true}})})}catch(err){error.value=err instanceof Error?err.message:'save_failed'}finally{saving.value=false}}
async function complete(){saving.value=true;try{await appApi('/app/api/onboarding/complete',{method:'POST'});location.assign('/app')}catch(err){error.value=err instanceof Error?err.message:'completion_failed'}finally{saving.value=false}}
onMounted(load)
</script>
<template><main class="onboarding-shell"><a class="brand" href="/app"><span>K</span>Klyrow</a><section class="setup-card"><p class="eyebrow">WORKSPACE SETUP</p><h1>Build a trustworthy sending foundation.</h1><p class="lede">Configure the identity, domain and API basics that Klyrow enforces before email leaves your workspace.</p><div v-if="loading" class="notice">Loading setup…</div><div v-else><div v-if="error" class="notice error" role="alert">{{error}}</div><section class="profile-grid"><label>Primary use case<select v-model="useCase"><option value="transactional">Transactional email</option><option value="marketing">Marketing campaigns</option><option value="mixed">Transactional + marketing</option><option value="agency">Agency / reseller</option></select></label><label>Company or team<input v-model="company" placeholder="Your company"></label><label>Team size<select v-model="teamSize"><option>1-5</option><option>6-25</option><option>26-100</option><option>100+</option></select></label></section><ol class="steps"><li v-for="([key,label],index) in steps" :key="key" :class="{done:state.checklist[key]}"><span class="step-number">{{state.checklist[key]?'✓':index+1}}</span><div><strong>{{label}}</strong><p>{{key==='domain'?'DNS ownership unlocks sending.':key==='sender'?'Only authorized addresses may send.':key==='api'?'Use scoped credentials for server integrations.':key==='test'?'Safe-mode testing proves the path before live delivery.':'Confirm how your team plans to use Klyrow.'}}</p></div><button :disabled="saving||state.checklist[key]" @click="saveStep(key,index)">{{state.checklist[key]?'Done':'Mark complete'}}</button></li></ol><div class="actions"><a href="/app">Do this later</a><button class="primary" :disabled="saving" @click="complete">Finish setup</button></div></div></section></main></template>
<style scoped>.onboarding-shell{min-height:100vh;background:#080808;color:#f7f8fa;padding:28px clamp(18px,5vw,72px) 70px;font-family:Inter,"Helvetica Neue","Segoe UI",Roboto,Arial,sans-serif}.brand{display:inline-flex;align-items:center;gap:10px;color:#f7f8fa;text-decoration:none;font-size:20px;font-weight:850}.brand span{display:grid;place-items:center;width:32px;height:32px;border-radius:4px;background:#ffd700;color:#080808}.setup-card{max-width:980px;margin:58px auto 0;border:1px solid #292b30;background:#0d0d0d;border-radius:6px;padding:clamp(24px,5vw,54px)}.eyebrow{color:#ffd700;font-size:11px;letter-spacing:.14em;font-weight:800}.setup-card h1{font-size:clamp(34px,5vw,58px);letter-spacing:-.055em;line-height:1.02;margin:9px 0 16px;max-width:760px}.lede{color:#c9cbd1;font-size:18px;max-width:680px;line-height:1.6}.profile-grid{display:grid;grid-template-columns:2fr 2fr 1fr;gap:12px;margin:35px 0}.profile-grid label{display:grid;gap:7px;color:#979aa2;font-size:12px}.profile-grid input,.profile-grid select{border:1px solid #34363b;background:#080808;color:#f7f8fa;border-radius:4px;padding:12px;font:inherit}.steps{list-style:none;margin:0;padding:0;border-top:1px solid #292b30}.steps li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:18px;padding:20px 0;border-bottom:1px solid #292b30}.step-number{display:grid;place-items:center;width:34px;height:34px;border:1px solid #494949;border-radius:4px;font-weight:800}.steps li.done .step-number{background:#ffd700;color:#080808;border-color:#ffd700}.steps strong{font-size:15px}.steps p{color:#979aa2;margin:5px 0 0;font-size:13px}.steps button{min-height:40px;border:1px solid #3a3a3a;background:#111;color:#c9cbd1;border-radius:4px;padding:0 13px;cursor:pointer}.steps button:disabled{opacity:.55}.actions{display:flex;justify-content:flex-end;align-items:center;gap:18px;margin-top:30px}.actions a{color:#c9cbd1}.primary{min-height:48px;border:1px solid #ffd700;background:#ffd700;color:#080808;border-radius:4px;padding:0 20px;font-weight:800;cursor:pointer}.notice{margin:24px 0;padding:13px;border:1px solid #343434}.notice.error{border-color:#6d2a2a;color:#ffaaaa}:focus-visible{outline:2px solid #ffd700;outline-offset:2px}@media(max-width:720px){.setup-card{margin-top:35px}.profile-grid{grid-template-columns:1fr}.steps li{grid-template-columns:auto 1fr}.steps li button{grid-column:2}.actions{justify-content:space-between}}</style>
