<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { appApi, getSession } from './api'

type Status={tenant_id:string;state:string;provider_mode?:string|null;organization?:string|null;server?:string|null;credential_fingerprint?:string|null;last_error?:string|null;attempts:number;updated_at?:string|null}
const status=ref<Status|null>(null), failures=ref<Status[]>([]), loading=ref(true), error=ref(''), working=ref(false)
const admin=computed(()=>location.pathname.startsWith('/admin/'))
async function load(){loading.value=true;error.value='';try{const session=await getSession();if(!session.authenticated){location.assign('/login?return_to='+encodeURIComponent(location.pathname));return}if(admin.value)failures.value=await appApi<Status[]>('/app/api/admin/provisioning/postal');else status.value=await appApi<Status>('/app/api/provisioning/postal')}catch(err){error.value=err instanceof Error?err.message:'provisioning_unavailable'}finally{loading.value=false}}
async function request(){working.value=true;try{status.value=await appApi<Status>('/app/api/provisioning/postal',{method:'POST'})}catch(err){error.value=err instanceof Error?err.message:'request_failed'}finally{working.value=false}}
async function retry(tenantId?:string){working.value=true;try{if(admin.value&&tenantId)await appApi(`/app/api/admin/provisioning/postal/${tenantId}/retry`,{method:'POST'});else status.value=await appApi<Status>('/app/api/provisioning/postal/retry',{method:'POST'});await load()}catch(err){error.value=err instanceof Error?err.message:'retry_failed'}finally{working.value=false}}
onMounted(load)
</script>
<template><main class="shell"><header><a class="brand" :href="admin?'/admin':'/app'"><span>K</span>Klyrow</a><a :href="admin?'/admin':'/app'">← Back</a></header><section class="card"><p class="eyebrow">POSTAL PROVISIONING</p><h1>{{admin?'Provisioning operations':'Sending infrastructure'}}</h1><p class="lede">Each Klyrow workspace receives an isolated Postal server credential. Provisioning creates resources in Development mode; it does not activate unrestricted live delivery.</p><div v-if="loading" class="notice">Loading provisioning state…</div><div v-else-if="error" class="notice error">{{error}}</div><template v-else-if="admin"><div v-if="!failures.length" class="notice good">No blocked or incomplete Postal mappings.</div><article v-for="item in failures" :key="item.tenant_id" class="row"><div><strong>{{item.tenant_id}}</strong><small>{{item.state}} · attempts {{item.attempts}} · {{item.last_error||'no error recorded'}}</small></div><button :disabled="working" @click="retry(item.tenant_id)">Retry</button></article></template><template v-else-if="status"><div class="state" :data-state="status.state"><span>{{status.state}}</span><strong>{{status.server||'Postal server not assigned yet'}}</strong><small>Mode: {{status.provider_mode||'pending'}} · attempts {{status.attempts}}</small></div><dl><div><dt>Organization</dt><dd>{{status.organization||'Pending'}}</dd></div><div><dt>Credential</dt><dd>{{status.credential_fingerprint||'Stored only after provisioning'}}</dd></div><div><dt>Last error</dt><dd>{{status.last_error||'None'}}</dd></div></dl><div class="actions"><button v-if="status.state==='NOT_REQUESTED'" class="primary" :disabled="working" @click="request">Provision sending workspace</button><button v-else-if="['BLOCKED','RETRYABLE_FAILURE'].includes(status.state)" class="primary" :disabled="working" @click="retry()">Retry provisioning</button><a v-if="status.state==='READY'" href="/app">Open dashboard →</a></div></template></section></main></template>
<style scoped>.shell{min-height:100vh;background:#080808;color:#f7f8fa;padding:28px clamp(18px,5vw,72px);font-family:Inter,"Helvetica Neue","Segoe UI",Roboto,Arial,sans-serif}header{display:flex;justify-content:space-between;align-items:center}header>a{color:#c9cbd1;text-decoration:none}.brand{display:flex;align-items:center;gap:10px!important;color:#f7f8fa!important;font-weight:850;font-size:20px}.brand span{display:grid;place-items:center;width:32px;height:32px;border-radius:4px;background:#ffd700;color:#080808}.card{max-width:900px;margin:58px auto;border:1px solid #292b30;background:#0d0d0d;border-radius:6px;padding:clamp(24px,5vw,54px)}.eyebrow{color:#ffd700;font-size:11px;letter-spacing:.14em;font-weight:800}.card h1{font-size:clamp(34px,5vw,56px);letter-spacing:-.05em;margin:8px 0 14px}.lede{color:#c9cbd1;line-height:1.6;max-width:720px}.notice,.state{margin:28px 0;padding:18px;border:1px solid #343434;border-radius:4px}.notice.error{border-color:#6d2a2a;color:#ffaaaa}.notice.good{border-color:#245f3e;color:#76dfa5}.state{display:grid;gap:7px}.state>span{color:#ffd700;font-size:12px;font-weight:800}.state>small,.row small{color:#979aa2}.state[data-state="READY"]{border-color:#245f3e}.state[data-state="BLOCKED"]{border-color:#6d2a2a}.row{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:18px 0;border-bottom:1px solid #292b30}.row small{display:block;margin-top:5px}.row button,.actions button{min-height:42px;padding:0 15px;border:1px solid #343434;background:#111;color:#c9cbd1;border-radius:4px;cursor:pointer}dl{margin:0}dl>div{display:grid;grid-template-columns:150px 1fr;gap:20px;padding:14px 0;border-bottom:1px solid #222}dt{color:#979aa2}dd{margin:0;word-break:break-word}.actions{display:flex;gap:15px;align-items:center;margin-top:28px}.actions .primary{background:#ffd700;border-color:#ffd700;color:#080808;font-weight:800}.actions a{color:#ffd700;text-decoration:none;font-weight:750}:focus-visible{outline:2px solid #ffd700;outline-offset:2px}@media(max-width:600px){dl>div{grid-template-columns:1fr;gap:5px}.row{align-items:flex-start;flex-direction:column}}</style>
