let token="";
const $=id=>document.getElementById(id), esc=value=>String(value??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
async function beginLogin(){location.assign("/login")}
async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token}`};if(options.body)headers["Content-Type"]="application/json";const r=await fetch(path,{...options,headers}),body=await r.json().catch(()=>null);if(!r.ok)throw Error((body&&body.detail)||`Request failed (${r.status})`);return body}
function render(value){if(Array.isArray(value)){if(!value.length)return '<p class="muted">No records yet.</p>';const keys=[...new Set(value.flatMap(x=>Object.keys(x||{})))].filter(k=>!/(hash|secret|verifier|token)/i.test(k)).slice(0,7);return `<div style="overflow:auto"><table><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll("_"," "))}</th>`).join("")}</tr></thead><tbody>${value.map(row=>`<tr>${keys.map(k=>`<td>${esc(typeof row[k]==="object"?JSON.stringify(row[k]):row[k])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}return `<pre>${esc(JSON.stringify(value,null,2))}</pre>`}
async function loadInto(path,id){$(id).innerHTML=render(await api(path))}function fail(e){$("error").textContent=e.message||String(e)}
customElements.define("resource-view",class extends HTMLElement{connectedCallback(){const id="resource-"+crypto.randomUUID(),path=this.getAttribute("path");this.innerHTML=`<div class="card"><h2>${esc(this.getAttribute("title"))}</h2><button class="secondary" id="${id}-button">Refresh</button><div id="${id}"><p class="muted">Open this section to load records.</p></div></div>`;$(id+"-button").onclick=()=>loadInto(path,id).catch(fail);this.dataset.output=id;this.dataset.path=path}});
async function dashboard(){const [a,u,g]=await Promise.all([api("/v1/analytics/overview"),api("/v1/usage"),api("/v1/settings/send-gate")]);$("messages").textContent=a.messages;$("profiles").textContent=a.profiles;$("deliveryRate").textContent=(a.delivery_rate*100).toFixed(1)+"%";$("quota").textContent=`${u.sent_24h} / ${u.quota}`;$("sendGate").textContent=g.sending_enabled?"Sending enabled":"Sending disabled by tenant safety gate";$("login").hidden=true;$("app").hidden=false}
$("signin").onclick=()=>beginLogin().catch(e=>$("message").textContent=e.message);$("logout").onclick=()=>location.assign("/login?logged_out=1");
$("nav").onclick=e=>{const b=e.target.closest("button[data-view]");if(!b)return;document.querySelectorAll("nav button").forEach(x=>{x.classList.remove("active");x.removeAttribute("aria-current")});document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");b.setAttribute("aria-current","page");const v=document.querySelector(`.view[data-view="${b.dataset.view}"]`);v.classList.add("active");$("title").textContent=b.textContent;$("main-content").focus();const r=v.querySelector("resource-view");if(r)loadInto(r.dataset.path,r.dataset.output).catch(fail)};
document.addEventListener("click",e=>{const b=e.target.closest(".refresh");if(b)loadInto(b.dataset.path,b.dataset.out).catch(fail)});
$("sendForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{$("sendOut").textContent=JSON.stringify(await api("/v1/messages",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(data)}),null,2)}catch(x){fail(x)}};
$("segmentForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.rules=JSON.parse(data.rules);try{$("segmentOut").textContent=JSON.stringify(await api("/v1/segments",{method:"POST",body:JSON.stringify(data)}),null,2)}catch(x){fail(x)}};
$("supportForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{$("supportOut").textContent=JSON.stringify(await api("/v1/support/tickets",{method:"POST",body:JSON.stringify(data)}),null,2)}catch(x){fail(x)}};
$("setupMfa").onclick=()=>api("/v1/auth/mfa/setup",{method:"POST"}).then(x=>$("settingsOut").innerHTML=render(x)).catch(fail);
